version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UCT
    open-pull-requests-limit: 5
    versioning-strategy: increase
