language: php

os:
  - linux

dist: bionic

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - nightly

env:
  - WP_VERSION=latest PHPUNIT_VERSION="^5.7"

services:
  - mysql

jobs:
  include:
    - php: 7.0
      dist: xenial
    - php: 5.6
      dist: xenial
    - name: "Coding Standards"
      php: 7.4
      install:
        - composer require --dev wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer
        # Counter wp-enforcer
        - rm -f ./phpcs.xml
      script:
        - vendor/bin/phpcs
    - name: "Static Analysis"
      php: 7.4
      install:
        - composer require --dev szepeviktor/phpstan-wordpress
      script:
        - vendor/bin/phpstan analyze
  allow_failures:
    - php: nightly

branches:
  only:
    - master

cache:
  directories:
    - "${HOME}/.composer/cache"

install:
  - bin/install-wp-tests.sh wordpress_test root "" localhost "${WP_VERSION}"
  - composer global require --dev "phpunit/phpunit=${PHPUNIT_VERSION}"

script:
  - "${HOME}/.composer/vendor/bin/phpunit"

notifications:
  email:
    on_success: never
    on_failure: change
